import json

class MemoGenerator:
    """Generates an executive Third-Party IT Risk Memo."""

    def generate_memo(self, vendor_name: str, airlock_res: dict, dora_res: dict) -> str:
        dora = dora_res.get("dora_article_28_compliance", {})
        memo = f"""# Executive Third-Party IT Risk Memo
**Target Vendor:** {vendor_name}  
**Framework:** DORA Article 28 / SOC 2 Type II / ISAE 3402  
**Generated by:** Vendor SOC / ISAE Auditor (`pietrodiwalsi-design/vendor-soc-isae-auditor`)

## 1. Risk Summary
- **Auditor Opinion:** {airlock_res.get('section_1_opinion')}
- **Subservice Method:** {airlock_res.get('subservice_method')}
- **Control Exceptions Found:** {airlock_res.get('section_4_exceptions_count')}
- **Residual Risk Tier:** {dora.get('risk_tier')} (Score: {dora.get('residual_tpm_risk_score')}/10)

## 2. DORA Article 28 Assessment
- **Status:** {dora.get('action_required')}
- **Fourth-Party Dependency Risk:** {'Yes (Carve-out subservice orgs require downstream review)' if dora.get('fourth_party_risk_identified') else 'No'}
"""
        return memo
